import javax.swing.*;
import java.awt.*;

public class ChangeLogin {
    public JFrame jFrame;
    private JTextField textField1;
    private JButton acceptNewLoginButton;
    private JButton deleteAccountButton;
    private JButton backToFirstMenuButton;

    public JPanel getChangeLogin() {
        return changeLogin;
    }

    private JPanel changeLogin;

    public ChangeLogin(JFrame jFrame, User user) {
        this.jFrame = jFrame;
        acceptNewLoginButton.addActionListener(e -> {
            String newLogin;
            newLogin = textField1.getText();
            try {
                DBOperations.changeLogin(user, newLogin);
                JOptionPane.showMessageDialog(new JFrame(),
                        "Dokonano zmiany loginu", "Sukces", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception exception) {
                JOptionPane.showMessageDialog(new JFrame(), "Podany login jest zajęty!", "Błąd", JOptionPane.ERROR_MESSAGE);
            }


        });
        backToFirstMenuButton.addActionListener(e -> {

            FirstMenu firstMenu = new FirstMenu(jFrame, user);

        });
        deleteAccountButton.addActionListener(e -> {

            DBOperations.deleteAccount(user.getId());
            JOptionPane.showMessageDialog(new JFrame(),
                    "Usunięto użytkownika", "Sukces", JOptionPane.INFORMATION_MESSAGE);
            jFrame.getContentPane().removeAll();
            Login login = new Login(jFrame);

        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        changeLogin = new JPanel();
        changeLogin.setLayout(new GridBagLayout());
        acceptNewLoginButton = new JButton();
        acceptNewLoginButton.setText("Zatwierdź nowy login");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        changeLogin.add(acceptNewLoginButton, gbc);
        textField1 = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        changeLogin.add(textField1, gbc);
        deleteAccountButton = new JButton();
        deleteAccountButton.setText("Usuń konto");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        changeLogin.add(deleteAccountButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Podaj nowy login");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        changeLogin.add(label1, gbc);
        backToFirstMenuButton = new JButton();
        backToFirstMenuButton.setText("Powrót do głównego menu");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        changeLogin.add(backToFirstMenuButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return changeLogin;
    }
}
