import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FinalMenu {
    private JButton zapiszGręButton;
    private JButton backToFirstMenuButton;

    private JLabel resultText;
    private JPanel jPanel3;
    private JLabel timeResult;
    private JButton finishButton;
    private User user;
    private Result result;
    private JFrame jFrame;

    public FinalMenu(Result result, User user, JFrame jFrame) {
        this.result = result;
        this.user = user;
        this.jFrame = jFrame;
        timeResult.setText(timeFormat());
        resultText.setText(Integer.toString(result.getScore()));
        zapiszGręButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DBOperations.addToDatabase(result);
                DBOperations.updateUser(user, result);
                JOptionPane.showMessageDialog(new JFrame(),
                        "Zapisano wynik", "Sukces", JOptionPane.INFORMATION_MESSAGE);

            }
        });
        finishButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        backToFirstMenuButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jFrame.getContentPane().removeAll();
                FirstMenu firstMenu = new FirstMenu(jFrame, user);
            }
        });
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    private String timeFormat() {
        float timePom = result.getTime();
        String sTime;
        if (timePom > 60) {
            timePom /= 60.0;
            int min = (int) timePom;
            float sec = timePom - min;
            sTime = Integer.toString(min) + " min " + String.valueOf(sec) + " sec";
        } else {
            sTime = String.valueOf(timePom) + " sec";
        }
        return sTime;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jPanel3 = new JPanel();
        jPanel3.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Koniec !");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        jPanel3.add(label1, gbc);
        zapiszGręButton = new JButton();
        zapiszGręButton.setText("Zapisz grę");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        jPanel3.add(zapiszGręButton, gbc);
        backToFirstMenuButton = new JButton();
        backToFirstMenuButton.setText("Powrót do menu głównego");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        jPanel3.add(backToFirstMenuButton, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Twój wynik to:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        jPanel3.add(label2, gbc);
        resultText = new JLabel();
        resultText.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        jPanel3.add(resultText, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Czas:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        jPanel3.add(label3, gbc);
        timeResult = new JLabel();
        timeResult.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        jPanel3.add(timeResult, gbc);
        finishButton = new JButton();
        finishButton.setText("Zakończ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        jPanel3.add(finishButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel3;
    }
}
