import javax.persistence.EntityManagerFactory;
import javax.swing.*;
import java.awt.*;

public class FirstMenu {
    private JButton zacznijGręButton;
    private User user;

    private JPanel panel1;
    private JButton changeLoginButton;
    private JButton gameListButton;
    JFrame jFrame;
    private EntityManagerFactory managerFactory;

    public FirstMenu(JFrame jFrame1, User user, EntityManagerFactory managerFactory1) {
        this.jFrame = jFrame1;
        this.user = user;
        this.managerFactory = managerFactory1;
        jFrame.setPreferredSize(new Dimension(400, 200));
        jFrame.setContentPane(panel1);
        jFrame.revalidate();
        jFrame.pack();
        zacznijGręButton.addActionListener(e -> {
            jFrame.getContentPane().removeAll();
            DifficultChoice difficultChoice = new DifficultChoice(jFrame, user, managerFactory);
            jFrame.setContentPane(difficultChoice.getJpanel2());
            jFrame.setPreferredSize(new Dimension(400, 300));
            jFrame.pack();
            jFrame.revalidate();
        });
        changeLoginButton.addActionListener(e -> {

            jFrame.getContentPane().removeAll();
            ChangeLogin changeLogin = new ChangeLogin(jFrame, user, managerFactory);
            jFrame.setContentPane(changeLogin.getChangeLogin());
            jFrame.pack();
            jFrame.revalidate();

        });
        gameListButton.addActionListener(e -> {
            jFrame.getContentPane().removeAll();

            //GameList list = new GameList(user,jFrame);
            jFrame.setPreferredSize(new Dimension(600, 300));
            //jFrame.setContentPane(list.getjPanel());
            GList gList = new GList(jFrame, user, managerFactory);
            jFrame.setContentPane(gList.getPanelList());
            jFrame.revalidate();
            jFrame.pack();


        });

    }


    public JPanel getPanel1() {
        return panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 80));
        zacznijGręButton = new JButton();
        zacznijGręButton.setText("Nowa gra");
        zacznijGręButton.setVerticalTextPosition(0);
        panel1.add(zacznijGręButton);
        gameListButton = new JButton();
        gameListButton.setText("Lista zagranych gier");
        panel1.add(gameListButton);
        changeLoginButton = new JButton();
        changeLoginButton.setHorizontalTextPosition(0);
        changeLoginButton.setText("Edytuj dane");
        panel1.add(changeLoginButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
